//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTEZIAN_WELL
    {
        public int OBJECTID { get; set; }
        public string REPER_NO { get; set; }
        public Nullable<decimal> IRRIGATED_AREA { get; set; }
        public Nullable<decimal> DEPTH { get; set; }
        public Nullable<decimal> NUMBER_ { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<int> PRODUCTIVITY { get; set; }
        public Nullable<int> WELL_TYPE_ID { get; set; }
        public Nullable<int> ASSIGMENT_ID { get; set; }
        public Nullable<int> ACTIVITY_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> PUMPSTATION_BRAND_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
        public Nullable<int> SIB_ID { get; set; }
        public Nullable<decimal> POINT_X { get; set; }
        public Nullable<decimal> POINT_Y { get; set; }
        public Nullable<decimal> POINT_Z { get; set; }
        public Nullable<decimal> POINT_M { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual ASSIGMENT ASSIGMENT { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual PUMPSTATION_BRAND PUMPSTATION_BRAND { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REGION REGION1 { get; set; }
        public virtual SIB SIB { get; set; }
        public virtual WELL_TYPE WELL_TYPE { get; set; }
    }
}
