//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHANNEL()
        {
            this.CHANNEL_SIBS = new HashSet<CHANNEL_SIBS>();
            this.CHANNELS1 = new HashSet<CHANNEL>();
        }
    
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        public Nullable<decimal> DEVICE_SUM { get; set; }
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        public Nullable<decimal> GIS_LENGTH { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> SERVED_AREAHA { get; set; }
        public Nullable<decimal> SHAPE_STLength__ { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> ASSIGMENT_ID { get; set; }
        public Nullable<int> ACTIVITY_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> TECHNICAL_ID { get; set; }
        public Nullable<int> SERVED_REGION_ID { get; set; }
        public Nullable<int> KIND_ID { get; set; }
        public Nullable<int> COVER_TYPE_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public Nullable<int> SOURCE_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual ASSIGMENT ASSIGMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANNEL_SIBS> CHANNEL_SIBS { get; set; }
        public virtual CHANNEL_TYPES CHANNEL_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANNEL> CHANNELS1 { get; set; }
        public virtual CHANNEL CHANNEL1 { get; set; }
        public virtual COVER_TYPES COVER_TYPES { get; set; }
        public virtual KIND KIND { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REGION REGION1 { get; set; }
        public virtual REGION REGION2 { get; set; }
        public virtual TECHNICAL_TYPE TECHNICAL_TYPE { get; set; }
    }
}
