//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> ACTIVITY_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> TECHNICAL_TYPE_ID { get; set; }
        public Nullable<int> SECURITY_TYPE_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public Nullable<int> SIBS_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
        public Nullable<int> NETWORK_TYPE_ID { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<decimal> SERVED_AREA { get; set; }
        public Nullable<int> CHANNEL_ID { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual NETWORK_TYPE NETWORK_TYPE { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual VILLAGE VILLAGE { get; set; }
        public virtual TECHNICAL_TYPE TECHNICAL_TYPE { get; set; }
        public virtual SECURITY_TYPE SECURITY_TYPE { get; set; }
    }
}
