//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRENAJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRENAJ()
        {
            this.DRENAJ1 = new HashSet<DRENAJ>();
            this.DRENAJ_SIBS = new HashSet<DRENAJ_SIBS>();
        }
    
        public int OBJECTID { get; set; }
        public Nullable<decimal> WATERPROOF_WIDTH { get; set; }
        public Nullable<decimal> SERVED_AREA { get; set; }
        public Nullable<decimal> DEVICE_SUM { get; set; }
        public Nullable<decimal> WATER_CAPABILITY { get; set; }
        public Nullable<decimal> FACTICAL_LENGTH { get; set; }
        public string NAME { get; set; }
        public string WATER_CONSUPTION { get; set; }
        public Nullable<decimal> GISLENGTH { get; set; }
        public string NOTE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> KIND_ID { get; set; }
        public Nullable<int> CHANNEL_TYPE_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public Nullable<int> TECHNICAL_CONDINITION_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> ACTIVITY_ID { get; set; }
        public Nullable<int> ASSIGMENT_ID { get; set; }
        public Nullable<int> RECIVER_ID { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
    
        public virtual ACTIVITY ACTIVITY { get; set; }
        public virtual ASSIGMENT ASSIGMENT { get; set; }
        public virtual CHANNEL_TYPES CHANNEL_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRENAJ> DRENAJ1 { get; set; }
        public virtual DRENAJ DRENAJ2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRENAJ_SIBS> DRENAJ_SIBS { get; set; }
        public virtual KIND KIND { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REGION REGION1 { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual TECHNICAL_TYPE TECHNICAL_TYPE { get; set; }
    }
}
