//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MelorEntities : DbContext
    {
        public MelorEntities()
            : base("name=MelorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVITY> ACTIVITies { get; set; }
        public virtual DbSet<ARTEZIAN_WELL> ARTEZIAN_WELL { get; set; }
        public virtual DbSet<ASSIGMENT> ASSIGMENTs { get; set; }
        public virtual DbSet<BRAND_OF_AGGREGATE> BRAND_OF_AGGREGATE { get; set; }
        public virtual DbSet<BUILDING> BUILDINGS { get; set; }
        public virtual DbSet<CHANNEL_SIBS> CHANNEL_SIBS { get; set; }
        public virtual DbSet<CHANNEL_TYPES> CHANNEL_TYPES { get; set; }
        public virtual DbSet<CHANNEL> CHANNELS { get; set; }
        public virtual DbSet<COVER_TYPES> COVER_TYPES { get; set; }
        public virtual DbSet<DEVICE> DEVICEs { get; set; }
        public virtual DbSet<DRENAJ> DRENAJs { get; set; }
        public virtual DbSet<DRENAJ_SIBS> DRENAJ_SIBS { get; set; }
        public virtual DbSet<ENGINE_BRAND> ENGINE_BRAND { get; set; }
        public virtual DbSet<ENGINE_KIND> ENGINE_KIND { get; set; }
        public virtual DbSet<EXPLOITATION_ROAD> EXPLOITATION_ROAD { get; set; }
        public virtual DbSet<KIND> KINDs { get; set; }
        public virtual DbSet<NETWORK_TYPE> NETWORK_TYPE { get; set; }
        public virtual DbSet<PIPELINE_MATERIAL> PIPELINE_MATERIAL { get; set; }
        public virtual DbSet<PLACED_SOURCE> PLACED_SOURCE { get; set; }
        public virtual DbSet<PROPERTY> PROPERTies { get; set; }
        public virtual DbSet<PROPERTY_TYPE> PROPERTY_TYPE { get; set; }
        public virtual DbSet<PUMP_KIND> PUMP_KIND { get; set; }
        public virtual DbSet<PUMP_TYPE> PUMP_TYPE { get; set; }
        public virtual DbSet<PUMPSTATION> PUMPSTATIONs { get; set; }
        public virtual DbSet<PUMPSTATION_BRAND> PUMPSTATION_BRAND { get; set; }
        public virtual DbSet<REGION_TYPE> REGION_TYPE { get; set; }
        public virtual DbSet<REGION> REGIONS { get; set; }
        public virtual DbSet<RIVERBAND> RIVERBANDs { get; set; }
        public virtual DbSet<SIB> SIBS { get; set; }
        public virtual DbSet<TECHNICAL_TYPE> TECHNICAL_TYPE { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERSMAINPAGE> USERSMAINPAGES { get; set; }
        public virtual DbSet<VILLAGE> VILLAGEs { get; set; }
        public virtual DbSet<WELL> WELLs { get; set; }
        public virtual DbSet<WELL_TYPE> WELL_TYPE { get; set; }
        public virtual DbSet<WINTERPASTURE> WINTERPASTURES { get; set; }
        public virtual DbSet<SECURITY_TYPE> SECURITY_TYPE { get; set; }
    }
}
