//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUMPSTATION
    {
        public int OBJECTID { get; set; }
        public Nullable<decimal> POWER { get; set; }
        public Nullable<decimal> PRODUCTIVITY { get; set; }
        public string PURPOSEFUL { get; set; }
        public string NAME { get; set; }
        public string PIPELINE { get; set; }
        public Nullable<decimal> PIPELINE_LENGHT { get; set; }
        public string ENGINE_INSTALL_DATE { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> PLACED_SOURCE_ID { get; set; }
        public Nullable<int> PUMP_KIND_ID { get; set; }
        public Nullable<int> PUMP_TYPE_ID { get; set; }
        public Nullable<int> BRAND_OF_AGGREGATE_ID { get; set; }
        public Nullable<int> PIPELINE_DIAMETER_ID { get; set; }
        public Nullable<int> PIPELINE_MATERIAL_ID { get; set; }
        public Nullable<int> ENGINE_BRAND_ID { get; set; }
        public Nullable<int> ENGINE_KIND_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> ASSIGMENT_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public Nullable<int> SIBS_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
        public Nullable<decimal> SERVED_AREA { get; set; }
        public Nullable<int> AGREGAT_SUM { get; set; }
    
        public virtual ASSIGMENT ASSIGMENT { get; set; }
        public virtual BRAND_OF_AGGREGATE BRAND_OF_AGGREGATE { get; set; }
        public virtual ENGINE_BRAND ENGINE_BRAND { get; set; }
        public virtual ENGINE_KIND ENGINE_KIND { get; set; }
        public virtual PIPELINE_MATERIAL PIPELINE_MATERIAL { get; set; }
        public virtual PLACED_SOURCE PLACED_SOURCE { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual PUMP_KIND PUMP_KIND { get; set; }
        public virtual PUMP_TYPE PUMP_TYPE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual VILLAGE VILLAGE { get; set; }
        public virtual SIB SIB { get; set; }
    }
}
