//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIVERBAND
    {
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> COVER_TYPE_ID { get; set; }
        public Nullable<int> TECHNICAL_TYPE_ID { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> SSI_ID { get; set; }
        public Nullable<int> ASSIGMENT_ID { get; set; }
        public Nullable<int> PLACED_SOURCE_ID { get; set; }
        public Nullable<int> REGIONS_ID { get; set; }
        public Nullable<int> SIBS_ID { get; set; }
        public Nullable<int> EXPLONATION_DATE { get; set; }
        public Nullable<int> SECURITY_TYPE_ID { get; set; }
    
        public virtual ASSIGMENT ASSIGMENT { get; set; }
        public virtual COVER_TYPES COVER_TYPES { get; set; }
        public virtual PLACED_SOURCE PLACED_SOURCE { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual VILLAGE VILLAGE { get; set; }
        public virtual SIB SIB { get; set; }
        public virtual TECHNICAL_TYPE TECHNICAL_TYPE { get; set; }
    }
}
