//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meliogis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VILLAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VILLAGE()
        {
            this.DEVICEs = new HashSet<DEVICE>();
            this.PUMPSTATIONs = new HashSet<PUMPSTATION>();
            this.RIVERBANDs = new HashSet<RIVERBAND>();
            this.WINTERPASTURES = new HashSet<WINTERPASTURE>();
        }
    
        public int OBJECTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> REL_ID { get; set; }
        public Nullable<int> REGION_TYPE_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICE> DEVICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUMPSTATION> PUMPSTATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIVERBAND> RIVERBANDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WINTERPASTURE> WINTERPASTURES { get; set; }
    }
}
